### ISSUE TITLE
Cygwin: ERROR flag name (help) is reserved

### ISSUE THREAD

**Issue by agross** [nvie/gitflow#46] opened 2010-08-24 22:55 UTC
Just installed gitflow under Cygwin (using zsh). When I `git flow init` the repository I first got the following error:
`flags:FATAL unable to determine getopt version`

I needed to install the `util-linux` package which got me `getopt (enhanced) 1.1.4` and was a bit difficult to find in Cygwin's package list. Perhaps this could be added to the readme.

Now with getopt in place I still cannot initialize the gitflow repository. The new error messages read as follows:

```
$ git flow init
flags:ERROR flag name (help) is reserved
flags:FATAL unrecognized option (,)
```

**Comment by nvie** [comment] 2010-08-25 19:20
This is a duplicate of http://github.com/nvie/gitflow/issues/issue/28.

**Comment by agross** [comment] 2010-08-25 20:06
Unfortunately the workaround mentioned in #28 doesn't work here.

**Comment by nvie** [comment] 2010-08-25 20:51
This is a bug that is due to the fact that shFlags is probably not working on Cygwin. Unfortunately, I have no Windows machines, so I can't test/analyse this behaviour. Nonetheless, it seems to be related to the limitations of the shFlags implementation.

Does anybody using Cygwin have a clue about this one?

**Closed as completed** 2010-08-26 02:20 UTC

**Comment by agross** [comment] 2010-08-30 14:37
Seems I've fallen victim to my exported `GREP_OPTIONS`. In my (zsh) shell these include `--ignore-case` which causes shFlags to consider the auto-defined "help" flags to be reserved.

I could work around the issue by including `unset GREP_OPTIONS` in git-flow's `main()` function.
