### ISSUE TITLE
hotfix doesn't merge in release branch

### ISSUE THREAD

**Issue by darkpotpot** [nvie/gitflow#61] opened 2010-10-20 10:17 UTC
Hello,

it's been 2 month I've been using gitflow and I think there is a missing stuff in hotifxes.

If I have a only develop and master and I create a hotfix with gitflow, everything is fine and the hotfix is merged on master and develop when finished,

But if I have develop, master and a release branch, the hotfix is only merged in develop and master. My release branch does not have the hotfix merged in it.

Is it something normal ? Is there an optional argument to allow this behavior ?

Or maybe it was just something which was not present in oldest version, since I didn't have the latest version of gitflow when I did my hotfix.

Thanks.

**Comment by nvie** [comment] 2010-10-20 11:04
Closing this as it's a duplicate of #3.

**Closed as completed by nvie** 2010-10-20 11:04 UTC
