### ISSUE TITLE
"git flow feature start" doesn't work

### ISSUE THREAD

**Issue by denikus** [nvie/gitflow#125] opened 2011-05-11 16:38 UTC
git flow init - works fine.

After initialization, I've run:
git branch --set-upstream develop origin/develop

And I've tried to start new feature:

git flow feature start main_page_html

But it show:

"No feature branches exist.

You can start a new feature branch:

 git flow feature start <name> [<base>]"

Also

"git flow init -f " command show me:
Unknown subcommand: '-f'

Something wrong with git flow but I can't find source of the problem.

git flow version - 0.4.1  
OS: freebsd

**Comment by nvie** [comment] 2011-05-11 21:17
Looks like a problem with the flag parser. Could you try running "git flow feature" ?

Cheers,
Vincent

**Comment by denikus** [comment] 2011-05-11 21:43
"git flow feature" - result same as running "git flow feature start new_feateure".

"no feature branches exists"

It seems that git flow ignore options.

**Comment by kixx** [comment] 2011-07-06 14:52
The source of the problem is that on FreeBSD the /bin/sh shell is a proper Bourne shell, unlike most Linux distributions where it is just a link to a bash shell. Therefore the $SUBACTION testing condition here: https://github.com/kostiklv/gitflow/blob/develop/git-flow#L97 will always fail, thus all subcommands will default to the list subaction which produces the above mentioned error message

**Comment by nvie** [comment] 2011-07-11 15:14
Fixed in 06e854ab1257c87f52632d367cc85345cddb863f by @kixx. Thanks!

**Closed as completed by nvie** 2011-07-11 15:14 UTC
